"""Generate C# references for the extended parity tests (osu!standard, mania, catch).

For each map in the manifest and each of the 7 mod combos, runs the C#
PerformanceCalculator `simulate <mode>` CLI (lazer, full-combo SS, 0 misses,
100% accuracy by default) and records BOTH attribute sets from that single
authoritative run:

  - difficulty_attributes  -> consumed by tests/difficulty.rs::ext_<mode>
  - performance_attributes -> consumed by tests/performance.rs::ext_<mode>

Values are emitted as shortest round-trip decimals (bit-exact when re-parsed
via `f64::from_str`). JSON `null` (e.g. `score_based_estimated_miss_count`)
is emitted as Rust `None`.

Usage:
    python gen_ext_refs.py <mode> <manifest.txt> <out.rs>

`mode` is one of: osu, mania, catch.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLI_DIR = ROOT.parent / "osu-tools" / "PerformanceCalculator"

# (rust mod label (diagnostics only), rust mod flag bits, CLI -m args)
COMBOS = [
    ("NM", 0, ""),
    ("HR", 16, "hr"),
    ("DT", 64, "dt"),
    ("HD", 8, "hd"),
    ("FL", 1024, "fl"),
    ("HD_EZ", 8 | 2, "hd ez"),
    ("HD_FL", 8 | 1024, "hd fl"),
]

# mode -> (Rust struct name, Rust const name)
MODES = {
    "osu": ("ExtRef", "EXT_REFS"),
    "mania": ("ManiaExtRef", "MANIA_EXT_REFS"),
    "catch": ("CatchExtRef", "CATCH_EXT_REFS"),
}


def run_cli(beatmap: Path, mods: str, mode: str):
    cmd = ["dotnet", "run", "--no-build", "--", "simulate", mode, str(beatmap.resolve())]
    for mod in mods.split():
        cmd += ["-m", mod]
    cmd += ["-j"]
    r = subprocess.run(cmd, cwd=CLI_DIR, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"CLI failed for {beatmap} {mode} mods={mods!r}: {r.stderr.strip()[:500]}")
    data = json.loads(r.stdout)
    return data["difficulty_attributes"], data["performance_attributes"]


def _f(v) -> str:
    """Shortest round-trip decimal of a numeric JSON value."""
    return repr(float(v))


def fmt_diff(fields: dict) -> str:
    parts = [f'("{k}", {json.dumps(_f(fields[k]))})' for k in sorted(fields)]
    return "[" + ", ".join(parts) + "]"


def fmt_perf(fields: dict) -> str:
    parts = []
    for k in sorted(fields):
        v = fields[k]
        if v is None:
            parts.append(f'("{k}", None)')
        else:
            parts.append(f'("{k}", Some({json.dumps(_f(v))}))')
    return "[" + ", ".join(parts) + "]"


def main() -> None:
    mode = sys.argv[1]
    struct_name, const_name = MODES[mode]
    manifest = Path(sys.argv[2])
    out = Path(sys.argv[3])
    out.parent.mkdir(parents=True, exist_ok=True)

    maps = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        maps.append(Path(line.split()[0]))

    lines = [
        "// GENERATED by scripts/gen_ext_refs.py - do not edit by hand.",
        f"// C# refs via `dotnet run --no-build -- simulate {mode} <map> -m <mods> -j` (lazer, full-combo SS).",
        f"// Consumed by tests/difficulty.rs::ext_{mode} and tests/performance.rs::ext_{mode}.",
        "",
        f"pub struct {struct_name} {{",
        "    pub mods: u32,",
        "    pub path: &'static str,",
        "    pub difficulty: &'static [(&'static str, &'static str)],",
        "    pub performance: &'static [(&'static str, Option<&'static str>)],",
        "}",
        "",
        f"pub const {const_name}: &[{struct_name}] = &[",
    ]

    for beatmap in maps:
        rel = beatmap.resolve().relative_to(ROOT.resolve()).as_posix()
        for cname, flag, mods in COMBOS:
            diff, perf = run_cli(beatmap, mods, mode)
            lines.append(f"    // {beatmap.name} {cname}")
            lines.append(
                f"    {struct_name} {{ mods: {flag}, path: {json.dumps(rel)}, "
                f"difficulty: &{fmt_diff(diff)}, performance: &{fmt_perf(perf)} }},",
            )
    lines.append("];")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} for {len(maps)} map(s)")


if __name__ == "__main__":
    main()
