"""Generate C# references for the non-full-combo (lazer) performance parity test.

The committed SS gate (tests/data/ext_refs.rs) covers full-combo / 0-miss plays,
where `effective_miss_count`, `combo_based_estimated_miss_count`, the aim/speed
miss penalties, slider breaks, the accuracy pp-component and the flashlight
combo scaling are all 0/None. This generator adds one non-full-combo case per
(map, mod combo): an explicit hit-result count set with o/m/miss > 0 and
combo < max combo, so accuracy < 1.0 and every accuracy-dependent path runs.

Pinned counts (per map with `obj` objects, `sl` sliders, `lt` large ticks and
`mc` max combo), all guaranteed in range with `combo <= mc - misses`:

    o       = max(1, obj // 25)
    m       = max(1, obj // 50)
    miss    = max(1, obj // 50)
    g       = obj - o - m - miss
    se      = sl - max(1, sl // 25)      (slider tails hit)
    lt_hit  = lt - min(lt, max(1, lt // 25))   (large ticks hit)
    combo   = (mc - miss) // 2

Both sides pin the same counts, so the derived accuracy matches bit-for-bit
(Rust derives it from the hit results via WithSliderAcc; C# uses GetAccuracy).

C# CLI flags (large-tick-misses / slider-tail-misses are the *missed* counts):
    --goods o --mehs m -X miss --large-tick-misses (lt - lt_hit)
    --slider-tail-misses (sl - se) --combo combo -j

Usage:
    python gen_ext_acc_refs.py <manifest.txt> <out.rs>
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLI_DIR = ROOT.parent / "osu-tools" / "PerformanceCalculator"

# (rust mod label (diagnostics only), rust mod flag bits, CLI -m args)
COMBOS = [
    ("NM", 0, ""),
    ("HR", 16, "hr"),
    ("DT", 64, "dt"),
    ("HD", 8, "hd"),
    ("FL", 1024, "fl"),
    ("HD_EZ", 8 | 2, "hd ez"),
    ("HD_FL", 8 | 1024, "hd fl"),
]

# (filename, obj, sl, lt, max_combo) - from the Rust tick probe + C# `score.combo`.
MAPS = {
    "100.osu": (120, 34, 68, 222),
    "104.osu": (418, 43, 15, 476),
    "1016.osu": (240, 41, 320, 601),
    "10816.osu": (153, 67, 80, 300),
    "100133.osu": (552, 79, 82, 713),
    "111439.osu": (733, 212, 38, 983),
    "1000168.osu": (977, 332, 35, 1344),
    "1000747.osu": (1896, 798, 57, 2751),
    "1001410.osu": (182, 137, 159, 478),
    "1005957.osu": (1620, 951, 663, 3234),
    "1041682.osu": (719, 282, 468, 1469),
    "1044694.osu": (1238, 380, 159, 1777),
    "1068383.osu": (183, 39, 3, 225),
    "1138626.osu": (171, 157, 449, 777),
    "1231400.osu": (765, 379, 10, 1154),
    "1314568.osu": (620, 72, 62, 754),
    "2779605.osu": (424, 75, 34, 533),
    "2785319.osu": (601, 293, 15, 909),
}


def run_cli(beatmap: Path, mods: str, o: int, m: int, miss: int,
            lt: int, lt_hit: int, se: int, sl: int, combo: int):
    cmd = ["dotnet", "run", "--no-build", "--", "simulate", "osu", str(beatmap.resolve())]
    for mod in mods.split():
        cmd += ["-m", mod]
    cmd += [
        "--goods", str(o),
        "--mehs", str(m),
        "-X", str(miss),
        "--large-tick-misses", str(lt - lt_hit),
        "--slider-tail-misses", str(sl - se),
        "--combo", str(combo),
        "-j",
    ]
    r = subprocess.run(cmd, cwd=CLI_DIR, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"CLI failed for {beatmap} mods={mods!r}: {r.stderr.strip()[:500]}")
    data = json.loads(r.stdout)
    return data["score"], data["performance_attributes"], data["difficulty_attributes"]


def counts(obj: int, sl: int, lt: int, mc: int):
    o = max(1, obj // 25)
    m = max(1, obj // 50)
    miss = max(1, obj // 50)
    g = obj - o - m - miss
    se = sl - max(1, sl // 25)
    lt_hit = lt - min(lt, max(1, lt // 25))
    combo = (mc - miss) // 2
    assert g >= 0 and 0 <= se <= sl and 0 <= lt_hit <= lt and 0 <= combo <= mc - miss
    return g, o, m, miss, se, lt_hit, combo


def _f(v) -> str:
    return repr(float(v))


def fmt_perf(fields: dict) -> str:
    parts = []
    for k in sorted(fields):
        v = fields[k]
        if v is None:
            parts.append(f'("{k}", None)')
        else:
            parts.append(f'("{k}", Some({json.dumps(_f(v))}))')
    return "[" + ", ".join(parts) + "]"


def main() -> None:
    manifest = Path(sys.argv[1])
    out = Path(sys.argv[2])
    out.parent.mkdir(parents=True, exist_ok=True)

    map_paths = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        map_paths.append(Path(line.split()[0]))

    lines = [
        "// GENERATED by scripts/gen_ext_acc_refs.py - do not edit by hand.",
        "// C# refs for non-full-combo lazer plays (o/m/miss > 0, combo < max combo,",
        "// accuracy < 100%) via `dotnet run --no-build -- simulate osu <map> -m <mods>",
        "// --goods --mehs -X --large-tick-misses --slider-tail-misses --combo -j`.",
        "// Consumed by tests/performance.rs::ext_acc_osu.",
        "",
        "pub struct ExtAccRef {",
        "    pub mods: u32,",
        "    pub path: &'static str,",
        "    pub n300: u32,",
        "    pub n100: u32,",
        "    pub n50: u32,",
        "    pub misses: u32,",
        "    pub large_tick_hits: u32,",
        "    pub slider_end_hits: u32,",
        "    pub combo: u32,",
        "    pub performance: &'static [(&'static str, Option<&'static str>)],",
        "}",
        "",
        "pub const EXT_ACC_REFS: &[ExtAccRef] = &[",
    ]

    for beatmap in map_paths:
        rel = beatmap.resolve().relative_to(ROOT.resolve()).as_posix()
        obj, sl, lt, mc = MAPS[beatmap.name]
        g, o, m, miss, se, lt_hit, combo = counts(obj, sl, lt, mc)
        for cname, flag, mods in COMBOS:
            score, perf, diff = run_cli(beatmap, mods, o, m, miss, lt, lt_hit, se, sl, combo)
            # Sanity: C# must report back exactly the counts we pinned.
            st = score["statistics"]
            assert st["great"] == g and st["ok"] == o and st["meh"] == m, \
                f"{beatmap.name} {cname}: {st}"
            assert st["miss"] == miss, f"{beatmap.name} {cname}: {st}"
            assert st["large_tick_miss"] == lt - lt_hit, f"{beatmap.name} {cname}: {st}"
            assert st["slider_tail_hit"] == se, f"{beatmap.name} {cname}: {st}"
            assert score["combo"] == combo, f"{beatmap.name} {cname}: {score['combo']}"
            assert int(diff["max_combo"]) == mc, f"{beatmap.name} {cname}: {diff['max_combo']}"
            lines.append(f"    // {beatmap.name} {cname}")
            lines.append(
                f"    ExtAccRef {{ mods: {flag}, path: {json.dumps(rel)}, "
                f"n300: {g}, n100: {o}, n50: {m}, misses: {miss}, "
                f"large_tick_hits: {lt_hit}, slider_end_hits: {se}, combo: {combo}, "
                f"performance: &{fmt_perf(perf)} }},",
            )
    lines.append("];")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} for {len(map_paths)} map(s) x {len(COMBOS)} mod(s)")


if __name__ == "__main__":
    main()
