// GENERATED by scripts/gen_ext_refs.py - do not edit by hand.
// C# refs via `dotnet run --no-build -- simulate mania <map> -m <mods> -j` (lazer, full-combo SS).
// Consumed by tests/difficulty.rs::ext_mania and tests/performance.rs::ext_mania.

pub struct ManiaExtRef {
    pub mods: u32,
    pub path: &'static str,
    pub difficulty: &'static [(&'static str, &'static str)],
    pub performance: &'static [(&'static str, Option<&'static str>)],
}

pub const MANIA_EXT_REFS: &[ManiaExtRef] = &[
    // 1638954.osu NM
    ManiaExtRef { mods: 0, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("108.92297471705167"))] },
    // 1638954.osu HR
    ManiaExtRef { mods: 16, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("108.92297471705167"))] },
    // 1638954.osu DT
    ManiaExtRef { mods: 64, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "4.6072892053157295")], performance: &[("difficulty", Some("224.52717042937203")), ("pp", Some("224.52717042937203"))] },
    // 1638954.osu HD
    ManiaExtRef { mods: 8, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("108.92297471705167"))] },
    // 1638954.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("108.92297471705167"))] },
    // 1638954.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("54.46148735852584"))] },
    // 1638954.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1638954.osu", difficulty: &[("max_combo", "956.0"), ("star_rating", "3.358304846842773")], performance: &[("difficulty", Some("108.92297471705167")), ("pp", Some("108.92297471705167"))] },
    // 1000026.osu NM
    ManiaExtRef { mods: 0, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("308.74449651165895"))] },
    // 1000026.osu HR
    ManiaExtRef { mods: 16, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("308.74449651165895"))] },
    // 1000026.osu DT
    ManiaExtRef { mods: 64, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "7.2484618912392405")], performance: &[("difficulty", Some("656.2117967112646")), ("pp", Some("656.2117967112646"))] },
    // 1000026.osu HD
    ManiaExtRef { mods: 8, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("308.74449651165895"))] },
    // 1000026.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("308.74449651165895"))] },
    // 1000026.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("154.37224825582948"))] },
    // 1000026.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1000026.osu", difficulty: &[("max_combo", "4141.0"), ("star_rating", "5.188783583947255")], performance: &[("difficulty", Some("308.74449651165895")), ("pp", Some("308.74449651165895"))] },
    // 1001780.osu NM
    ManiaExtRef { mods: 0, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("497.6222804621096"))] },
    // 1001780.osu HR
    ManiaExtRef { mods: 16, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("497.6222804621096"))] },
    // 1001780.osu DT
    ManiaExtRef { mods: 64, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "8.84980731150792")], performance: &[("difficulty", Some("1026.6061611029086")), ("pp", Some("1026.6061611029086"))] },
    // 1001780.osu HD
    ManiaExtRef { mods: 8, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("497.6222804621096"))] },
    // 1001780.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("497.6222804621096"))] },
    // 1001780.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("248.8111402310548"))] },
    // 1001780.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1001780.osu", difficulty: &[("max_combo", "2242.0"), ("star_rating", "6.409696077378917")], performance: &[("difficulty", Some("497.6222804621096")), ("pp", Some("497.6222804621096"))] },
    // 1002277.osu NM
    ManiaExtRef { mods: 0, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("441.6902372998772"))] },
    // 1002277.osu HR
    ManiaExtRef { mods: 16, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("441.6902372998772"))] },
    // 1002277.osu DT
    ManiaExtRef { mods: 64, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "8.681416031778022")], performance: &[("difficulty", Some("983.397585616312")), ("pp", Some("983.397585616312"))] },
    // 1002277.osu HD
    ManiaExtRef { mods: 8, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("441.6902372998772"))] },
    // 1002277.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("441.6902372998772"))] },
    // 1002277.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("220.8451186499386"))] },
    // 1002277.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1002277.osu", difficulty: &[("max_combo", "11790.0"), ("star_rating", "6.079471244650901")], performance: &[("difficulty", Some("441.6902372998772")), ("pp", Some("441.6902372998772"))] },
    // 1976091.osu NM
    ManiaExtRef { mods: 0, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("162.38601934693747"))] },
    // 1976091.osu HR
    ManiaExtRef { mods: 16, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("162.38601934693747"))] },
    // 1976091.osu DT
    ManiaExtRef { mods: 64, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "5.3875087588255415")], performance: &[("difficulty", Some("336.16860279924924")), ("pp", Some("336.16860279924924"))] },
    // 1976091.osu HD
    ManiaExtRef { mods: 8, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("162.38601934693747"))] },
    // 1976091.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("162.38601934693747"))] },
    // 1976091.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("81.19300967346874"))] },
    // 1976091.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1976091.osu", difficulty: &[("max_combo", "2872.0"), ("star_rating", "3.9125694847942074")], performance: &[("difficulty", Some("162.38601934693747")), ("pp", Some("162.38601934693747"))] },
    // 1122855.osu NM
    ManiaExtRef { mods: 0, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("8.768037685476386"))] },
    // 1122855.osu HR
    ManiaExtRef { mods: 16, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("8.768037685476386"))] },
    // 1122855.osu DT
    ManiaExtRef { mods: 64, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.4762112717826228")], performance: &[("difficulty", Some("15.321793491126506")), ("pp", Some("15.321793491126506"))] },
    // 1122855.osu HD
    ManiaExtRef { mods: 8, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("8.768037685476386"))] },
    // 1122855.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("8.768037685476386"))] },
    // 1122855.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("4.384018842738193"))] },
    // 1122855.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1122855.osu", difficulty: &[("max_combo", "1002.0"), ("star_rating", "1.179029026354728")], performance: &[("difficulty", Some("8.768037685476386")), ("pp", Some("8.768037685476386"))] },
    // 1017155.osu NM
    ManiaExtRef { mods: 0, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("412.9312940773218"))] },
    // 1017155.osu HR
    ManiaExtRef { mods: 16, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("412.9312940773218"))] },
    // 1017155.osu DT
    ManiaExtRef { mods: 64, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "8.294538644936566")], performance: &[("difficulty", Some("887.9508891576597")), ("pp", Some("887.9508891576597"))] },
    // 1017155.osu HD
    ManiaExtRef { mods: 8, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("412.9312940773218"))] },
    // 1017155.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("412.9312940773218"))] },
    // 1017155.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("206.4656470386609"))] },
    // 1017155.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1017155.osu", difficulty: &[("max_combo", "2669.0"), ("star_rating", "5.900757531088703")], performance: &[("difficulty", Some("412.9312940773218")), ("pp", Some("412.9312940773218"))] },
    // 1006238.osu NM
    ManiaExtRef { mods: 0, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("394.62518987555706"))] },
    // 1006238.osu HR
    ManiaExtRef { mods: 16, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("394.62518987555706"))] },
    // 1006238.osu DT
    ManiaExtRef { mods: 64, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "8.092219067949845")], performance: &[("difficulty", Some("840.146008394527")), ("pp", Some("840.146008394527"))] },
    // 1006238.osu HD
    ManiaExtRef { mods: 8, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("394.62518987555706"))] },
    // 1006238.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("394.62518987555706"))] },
    // 1006238.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("197.31259493777853"))] },
    // 1006238.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1006238.osu", difficulty: &[("max_combo", "3094.0"), ("star_rating", "5.783440299504174")], performance: &[("difficulty", Some("394.62518987555706")), ("pp", Some("394.62518987555706"))] },
    // 1024723.osu NM
    ManiaExtRef { mods: 0, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("852.0453437931535"))] },
    // 1024723.osu HR
    ManiaExtRef { mods: 16, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("852.0453437931535"))] },
    // 1024723.osu DT
    ManiaExtRef { mods: 64, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "11.677302839500053")], performance: &[("difficulty", Some("1906.7054963138662")), ("pp", Some("1906.7054963138662"))] },
    // 1024723.osu HD
    ManiaExtRef { mods: 8, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("852.0453437931535"))] },
    // 1024723.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("852.0453437931535"))] },
    // 1024723.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("426.02267189657675"))] },
    // 1024723.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1024723.osu", difficulty: &[("max_combo", "8731.0"), ("star_rating", "8.143154322075365")], performance: &[("difficulty", Some("852.0453437931535")), ("pp", Some("852.0453437931535"))] },
    // 1038663.osu NM
    ManiaExtRef { mods: 0, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("496.48472848598965"))] },
    // 1038663.osu HR
    ManiaExtRef { mods: 16, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("496.48472848598965"))] },
    // 1038663.osu DT
    ManiaExtRef { mods: 64, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "9.001092556346343")], performance: &[("difficulty", Some("1066.2911705056376")), ("pp", Some("1066.2911705056376"))] },
    // 1038663.osu HD
    ManiaExtRef { mods: 8, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("496.48472848598965"))] },
    // 1038663.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("496.48472848598965"))] },
    // 1038663.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("248.24236424299482"))] },
    // 1038663.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1038663.osu", difficulty: &[("max_combo", "10732.0"), ("star_rating", "6.403187696003667")], performance: &[("difficulty", Some("496.48472848598965")), ("pp", Some("496.48472848598965"))] },
    // 298814.osu NM
    ManiaExtRef { mods: 0, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("85.32307881330193"))] },
    // 298814.osu HR
    ManiaExtRef { mods: 16, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("85.32307881330193"))] },
    // 298814.osu DT
    ManiaExtRef { mods: 64, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "3.9770568315317925")], performance: &[("difficulty", Some("168.57201475388027")), ("pp", Some("168.57201475388027"))] },
    // 298814.osu HD
    ManiaExtRef { mods: 8, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("85.32307881330193"))] },
    // 298814.osu FL
    ManiaExtRef { mods: 1024, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("85.32307881330193"))] },
    // 298814.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("42.66153940665097"))] },
    // 298814.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/298814.osu", difficulty: &[("max_combo", "3096.0"), ("star_rating", "2.958323943680106")], performance: &[("difficulty", Some("85.32307881330193")), ("pp", Some("85.32307881330193"))] },
    // 1569750.osu NM
    ManiaExtRef { mods: 0, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("213.8812276873323"))] },
    // 1569750.osu HR
    ManiaExtRef { mods: 16, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("213.8812276873323"))] },
    // 1569750.osu DT
    ManiaExtRef { mods: 64, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "6.156780104055972")], performance: &[("difficulty", Some("454.45876724267873")), ("pp", Some("454.45876724267873"))] },
    // 1569750.osu HD
    ManiaExtRef { mods: 8, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("213.8812276873323"))] },
    // 1569750.osu FL
    ManiaExtRef { mods: 1024, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("213.8812276873323"))] },
    // 1569750.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("106.94061384366616"))] },
    // 1569750.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/1569750.osu", difficulty: &[("max_combo", "5131.0"), ("star_rating", "4.41441133604656")], performance: &[("difficulty", Some("213.8812276873323")), ("pp", Some("213.8812276873323"))] },
    // 701563.osu NM
    ManiaExtRef { mods: 0, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("66.582625478179"))] },
    // 701563.osu HR
    ManiaExtRef { mods: 16, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("66.582625478179"))] },
    // 701563.osu DT
    ManiaExtRef { mods: 64, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "3.6752944045320364")], performance: &[("difficulty", Some("139.69118449311011")), ("pp", Some("139.69118449311011"))] },
    // 701563.osu HD
    ManiaExtRef { mods: 8, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("66.582625478179"))] },
    // 701563.osu FL
    ManiaExtRef { mods: 1024, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("66.582625478179"))] },
    // 701563.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("33.2913127390895"))] },
    // 701563.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/701563.osu", difficulty: &[("max_combo", "1551.0"), ("star_rating", "2.6672073430607153")], performance: &[("difficulty", Some("66.582625478179")), ("pp", Some("66.582625478179"))] },
    // 4275754.osu NM
    ManiaExtRef { mods: 0, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("37.4011542971727"))] },
    // 4275754.osu HR
    ManiaExtRef { mods: 16, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("37.4011542971727"))] },
    // 4275754.osu DT
    ManiaExtRef { mods: 64, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.7685929830967053")], performance: &[("difficulty", Some("69.28699560239218")), ("pp", Some("69.28699560239218"))] },
    // 4275754.osu HD
    ManiaExtRef { mods: 8, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("37.4011542971727"))] },
    // 4275754.osu FL
    ManiaExtRef { mods: 1024, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("37.4011542971727"))] },
    // 4275754.osu HD_EZ
    ManiaExtRef { mods: 10, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("18.70057714858635"))] },
    // 4275754.osu HD_FL
    ManiaExtRef { mods: 1032, path: "resources/4275754.osu", difficulty: &[("max_combo", "1004.0"), ("star_rating", "2.1285901943877312")], performance: &[("difficulty", Some("37.4011542971727")), ("pp", Some("37.4011542971727"))] },
];
