// GENERATED by scripts/gen_ext_refs.py - do not edit by hand.
// C# refs via `dotnet run --no-build -- simulate catch <map> -m <mods> -j` (lazer, full-combo SS).
// Consumed by tests/difficulty.rs::ext_catch and tests/performance.rs::ext_catch.

pub struct CatchExtRef {
    pub mods: u32,
    pub path: &'static str,
    pub difficulty: &'static [(&'static str, &'static str)],
    pub performance: &'static [(&'static str, Option<&'static str>)],
}

pub const CATCH_EXT_REFS: &[CatchExtRef] = &[
    // 2118524.osu NM
    CatchExtRef { mods: 0, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "3.2340182503279706")], performance: &[("pp", Some("112.72215339177879"))] },
    // 2118524.osu HR
    CatchExtRef { mods: 16, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "4.308291009137178")], performance: &[("pp", Some("220.18609645365825"))] },
    // 2118524.osu DT
    CatchExtRef { mods: 64, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "4.6192881825873275")], performance: &[("pp", Some("245.48176596381523"))] },
    // 2118524.osu HD
    CatchExtRef { mods: 8, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "3.2340182503279706")], performance: &[("pp", Some("135.26658407013454"))] },
    // 2118524.osu FL
    CatchExtRef { mods: 1024, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "3.2340182503279706")], performance: &[("pp", Some("157.89668358506805"))] },
    // 2118524.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "4.059198145823293")], performance: &[("pp", Some("293.1588776478542"))] },
    // 2118524.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/2118524.osu", difficulty: &[("max_combo", "730.0"), ("star_rating", "3.2340182503279706")], performance: &[("pp", Some("189.47602030208165"))] },
    // 1009515.osu NM
    CatchExtRef { mods: 0, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "2.7257005707045363")], performance: &[("pp", Some("81.05920049108148"))] },
    // 1009515.osu HR
    CatchExtRef { mods: 16, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "3.3829697075145324")], performance: &[("pp", Some("136.74513465248882"))] },
    // 1009515.osu DT
    CatchExtRef { mods: 64, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "3.936526193650206")], performance: &[("pp", Some("177.3604524196635"))] },
    // 1009515.osu HD
    CatchExtRef { mods: 8, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "2.7257005707045363")], performance: &[("pp", Some("98.48692743710284"))] },
    // 1009515.osu FL
    CatchExtRef { mods: 1024, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "2.7257005707045363")], performance: &[("pp", Some("114.42430224201749"))] },
    // 1009515.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "4.132464720814475")], performance: &[("pp", Some("308.43236186450775"))] },
    // 1009515.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1009515.osu", difficulty: &[("max_combo", "797.0"), ("star_rating", "2.7257005707045363")], performance: &[("pp", Some("139.02552558719847"))] },
    // 1008236.osu NM
    CatchExtRef { mods: 0, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "4.929058880749433")], performance: &[("pp", Some("268.64109067745846"))] },
    // 1008236.osu HR
    CatchExtRef { mods: 16, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "5.14878729555456")], performance: &[("pp", Some("301.36495574911055"))] },
    // 1008236.osu DT
    CatchExtRef { mods: 64, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "6.780579649665628")], performance: &[("pp", Some("598.8990085010211"))] },
    // 1008236.osu HD
    CatchExtRef { mods: 8, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "4.929058880749433")], performance: &[("pp", Some("288.1175735945159"))] },
    // 1008236.osu FL
    CatchExtRef { mods: 1024, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "4.929058880749433")], performance: &[("pp", Some("360.5039861989781"))] },
    // 1008236.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "4.682438786857974")], performance: &[("pp", Some("351.0098617855995"))] },
    // 1008236.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1008236.osu", difficulty: &[("max_combo", "367.0"), ("star_rating", "4.929058880749433")], performance: &[("pp", Some("386.640530355455"))] },
    // 2225824.osu NM
    CatchExtRef { mods: 0, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.242122238054852")], performance: &[("pp", Some("16.308893146297674"))] },
    // 2225824.osu HR
    CatchExtRef { mods: 16, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.8030752812377413")], performance: &[("pp", Some("32.577318501802615"))] },
    // 2225824.osu DT
    CatchExtRef { mods: 64, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.7586886809526798")], performance: &[("pp", Some("30.974242133466447"))] },
    // 2225824.osu HD
    CatchExtRef { mods: 8, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.242122238054852")], performance: &[("pp", Some("22.383956076594146"))] },
    // 2225824.osu FL
    CatchExtRef { mods: 1024, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.242122238054852")], performance: &[("pp", Some("21.270188912546597"))] },
    // 2225824.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.1324548574296147")], performance: &[("pp", Some("22.938250801030776"))] },
    // 2225824.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/2225824.osu", difficulty: &[("max_combo", "134.0"), ("star_rating", "1.242122238054852")], performance: &[("pp", Some("29.193334586742697"))] },
    // 1027894.osu NM
    CatchExtRef { mods: 0, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "6.598023753401167")], performance: &[("pp", Some("640.8787160293633"))] },
    // 1027894.osu HR
    CatchExtRef { mods: 16, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "7.488392021551169")], performance: &[("pp", Some("848.7808059538221"))] },
    // 1027894.osu DT
    CatchExtRef { mods: 64, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "9.280320875904703")], performance: &[("pp", Some("1493.5166865062174"))] },
    // 1027894.osu HD
    CatchExtRef { mods: 8, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "6.598023753401167")], performance: &[("pp", Some("687.3424321093358"))] },
    // 1027894.osu FL
    CatchExtRef { mods: 1024, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "6.598023753401167")], performance: &[("pp", Some("1144.569832203715"))] },
    // 1027894.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "5.878362904192594")], performance: &[("pp", Some("736.4864382421509"))] },
    // 1027894.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1027894.osu", difficulty: &[("max_combo", "3560.0"), ("star_rating", "6.598023753401167")], performance: &[("pp", Some("1227.5511614116874"))] },
    // 1000764.osu NM
    CatchExtRef { mods: 0, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "5.200802434087632")], performance: &[("pp", Some("312.43368796059286"))] },
    // 1000764.osu HR
    CatchExtRef { mods: 16, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "6.298235366595365")], performance: &[("pp", Some("480.1450484772701"))] },
    // 1000764.osu DT
    CatchExtRef { mods: 64, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "7.268990688557413")], performance: &[("pp", Some("717.2043745130838"))] },
    // 1000764.osu HD
    CatchExtRef { mods: 8, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "5.200802434087632")], performance: &[("pp", Some("339.77163565714477"))] },
    // 1000764.osu FL
    CatchExtRef { mods: 1024, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "5.200802434087632")], performance: &[("pp", Some("446.2996507715644"))] },
    // 1000764.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "4.432477755278413")], performance: &[("pp", Some("337.3071253631868"))] },
    // 1000764.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1000764.osu", difficulty: &[("max_combo", "901.0"), ("star_rating", "5.200802434087632")], performance: &[("pp", Some("485.3508702140764"))] },
    // 1000293.osu NM
    CatchExtRef { mods: 0, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.0224595268477907")], performance: &[("pp", Some("96.87268800341447"))] },
    // 1000293.osu HR
    CatchExtRef { mods: 16, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.6080103139792556")], performance: &[("pp", Some("151.1560631976074"))] },
    // 1000293.osu DT
    CatchExtRef { mods: 64, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "4.261679879742209")], performance: &[("pp", Some("202.0085356262404"))] },
    // 1000293.osu HD
    CatchExtRef { mods: 8, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.0224595268477907")], performance: &[("pp", Some("117.70031453837366"))] },
    // 1000293.osu FL
    CatchExtRef { mods: 1024, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.0224595268477907")], performance: &[("pp", Some("132.8705788654833"))] },
    // 1000293.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.4847138948497216")], performance: &[("pp", Some("213.02672445866904"))] },
    // 1000293.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1000293.osu", difficulty: &[("max_combo", "550.0"), ("star_rating", "3.0224595268477907")], performance: &[("pp", Some("161.43775142083334"))] },
    // 110693.osu NM
    CatchExtRef { mods: 0, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "5.3505214208574055")], performance: &[("pp", Some("320.19818025365134"))] },
    // 110693.osu HR
    CatchExtRef { mods: 16, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "6.027984348341673")], performance: &[("pp", Some("447.1313596203747"))] },
    // 110693.osu DT
    CatchExtRef { mods: 64, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "7.2255764217388005")], performance: &[("pp", Some("623.1112741744753"))] },
    // 110693.osu HD
    CatchExtRef { mods: 8, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "5.3505214208574055")], performance: &[("pp", Some("384.2378163043816"))] },
    // 110693.osu FL
    CatchExtRef { mods: 1024, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "5.3505214208574055")], performance: &[("pp", Some("465.0161324260518"))] },
    // 110693.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "4.890723484517522")], performance: &[("pp", Some("441.36402800200483"))] },
    // 110693.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/110693.osu", difficulty: &[("max_combo", "1048.0"), ("star_rating", "5.3505214208574055")], performance: &[("pp", Some("558.0193589112622"))] },
    // 1289886.osu NM
    CatchExtRef { mods: 0, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.061677002473591")], performance: &[("pp", Some("43.27657446125817"))] },
    // 1289886.osu HR
    CatchExtRef { mods: 16, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.8569535739202343")], performance: &[("pp", Some("91.51054681868344"))] },
    // 1289886.osu DT
    CatchExtRef { mods: 64, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.622229303130752")], performance: &[("pp", Some("81.74352991679454"))] },
    // 1289886.osu HD
    CatchExtRef { mods: 8, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.061677002473591")], performance: &[("pp", Some("48.686146268915444"))] },
    // 1289886.osu FL
    CatchExtRef { mods: 1024, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.061677002473591")], performance: &[("pp", Some("57.34604847805998"))] },
    // 1289886.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "1.7782187979981545")], performance: &[("pp", Some("51.17329216348593"))] },
    // 1289886.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1289886.osu", difficulty: &[("max_combo", "263.0"), ("star_rating", "2.061677002473591")], performance: &[("pp", Some("64.51430453781748"))] },
    // 1287064.osu NM
    CatchExtRef { mods: 0, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "6.1837199098781195")], performance: &[("pp", Some("437.1720706225207"))] },
    // 1287064.osu HR
    CatchExtRef { mods: 16, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "7.836968746053881")], performance: &[("pp", Some("772.6057301696563"))] },
    // 1287064.osu DT
    CatchExtRef { mods: 64, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "8.81627926170262")], performance: &[("pp", Some("948.2365539646611"))] },
    // 1287064.osu HD
    CatchExtRef { mods: 8, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "6.1837199098781195")], performance: &[("pp", Some("524.6064847470249"))] },
    // 1287064.osu FL
    CatchExtRef { mods: 1024, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "6.1837199098781195")], performance: &[("pp", Some("648.846415497239"))] },
    // 1287064.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "4.592929206712009")], performance: &[("pp", Some("397.7639167613773"))] },
    // 1287064.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1287064.osu", difficulty: &[("max_combo", "1245.0"), ("star_rating", "6.1837199098781195")], performance: &[("pp", Some("778.6156985966868"))] },
    // 1176539.osu NM
    CatchExtRef { mods: 0, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "4.403929423479749")], performance: &[("pp", Some("233.45873260530803"))] },
    // 1176539.osu HR
    CatchExtRef { mods: 16, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "7.284141093447479")], performance: &[("pp", Some("639.1341857458567"))] },
    // 1176539.osu DT
    CatchExtRef { mods: 64, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "5.9368543565327405")], performance: &[("pp", Some("501.640582958623"))] },
    // 1176539.osu HD
    CatchExtRef { mods: 8, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "4.403929423479749")], performance: &[("pp", Some("245.13166923557344"))] },
    // 1176539.osu FL
    CatchExtRef { mods: 1024, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "4.403929423479749")], performance: &[("pp", Some("331.8228342488329"))] },
    // 1176539.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "3.168928178048256")], performance: &[("pp", Some("168.22216839867215"))] },
    // 1176539.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/1176539.osu", difficulty: &[("max_combo", "857.0"), ("star_rating", "4.403929423479749")], performance: &[("pp", Some("348.41397596127456"))] },
    // 2571609.osu NM
    CatchExtRef { mods: 0, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "96.17288088703299")], performance: &[("pp", Some("177039.3840444829"))] },
    // 2571609.osu HR
    CatchExtRef { mods: 16, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "98.96118610993749")], performance: &[("pp", Some("189608.95276634782"))] },
    // 2571609.osu DT
    CatchExtRef { mods: 64, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "113.87438984244345")], performance: &[("pp", Some("292908.8389301213"))] },
    // 2571609.osu HD
    CatchExtRef { mods: 8, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "96.17288088703299")], performance: &[("pp", Some("187551.09747212406"))] },
    // 2571609.osu FL
    CatchExtRef { mods: 1024, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "96.17288088703299")], performance: &[("pp", Some("404042.069718614"))] },
    // 2571609.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "44.798575975955984")], performance: &[("pp", Some("54363.017692333895"))] },
    // 2571609.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/2571609.osu", difficulty: &[("max_combo", "21153.0"), ("star_rating", "96.17288088703299")], performance: &[("pp", Some("428032.0676081567"))] },
    // 3800907.osu NM
    CatchExtRef { mods: 0, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "2.267673406759664")], performance: &[("pp", Some("59.70092414864834"))] },
    // 3800907.osu HR
    CatchExtRef { mods: 16, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "4.519655461247145")], performance: &[("pp", Some("233.43200935455948"))] },
    // 3800907.osu DT
    CatchExtRef { mods: 64, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "3.1593463471479106")], performance: &[("pp", Some("105.74028333323308"))] },
    // 3800907.osu HD
    CatchExtRef { mods: 8, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "2.267673406759664")], performance: &[("pp", Some("98.50652484526975"))] },
    // 3800907.osu FL
    CatchExtRef { mods: 1024, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "2.267673406759664")], performance: &[("pp", Some("78.41370121564897"))] },
    // 3800907.osu HD_EZ
    CatchExtRef { mods: 10, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "1.2428151864496797")], performance: &[("pp", Some("31.51527324280773"))] },
    // 3800907.osu HD_FL
    CatchExtRef { mods: 1032, path: "resources/3800907.osu", difficulty: &[("max_combo", "191.0"), ("star_rating", "2.267673406759664")], performance: &[("pp", Some("129.3826070058208"))] },
];
